site_name: Linux Training Course
site_description: Linux Internals training track
docs_dir: content
site_dir: dist

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - toc.integrate
    - search.suggest
    - content.code.copy

plugins:
  - search
  - roamlinks

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true
